controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_captcha_generate:
    path: /captcha/generate
    controller: App\Controller\CaptchaController::generateCaptcha
